# Generated by Django 5.2.5 on 2025-08-24 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0003_coursetype_facultyprofile_committeedepot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('lecturer', models.CharField(default='', max_length=255)),
                ('committee', models.CharField(default='', max_length=255)),
                ('multilecture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('committe_pk', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='faculty.committee')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dpt_courses', to='faculty.department')),
                ('lecturer_pk', models.ForeignKey(default=207, on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyprofile')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuestionDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Please fill this field', max_length=255)),
                ('question_text', models.TextField()),
                ('general_feedback', models.TextField(blank=True, null=True)),
                ('default_grade', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('hidden', models.BooleanField(default=False)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('single', models.BooleanField(default=True)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('answer_numbering', models.CharField(default='ABCD', max_length=10)),
                ('show_standard_instruction', models.BooleanField(default=True)),
                ('correct_feedback', models.TextField(default='Doğru Cevap.')),
                ('partially_correct_feedback', models.TextField(default='Kısmi olarak doğru.')),
                ('incorrect_feedback', models.TextField(default='Yanlış cevap.')),
                ('show_num_correct', models.CharField(default='Yes', max_length=10)),
                ('answer_1_fraction', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('answer_1_text', models.TextField(default='Please fill this field')),
                ('answer_2_fraction', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('answer_2_text', models.TextField(default='Please fill this field')),
                ('answer_3_fraction', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('answer_3_text', models.TextField(default='Please fill this field')),
                ('answer_4_fraction', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('answer_4_text', models.TextField(default='Please fill this field')),
                ('answer_5_fraction', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('answer_5_text', models.TextField(default='Please fill this field')),
                ('correct_answer', models.CharField(default='Please fill this field', max_length=10)),
                ('tag_1', models.CharField(default='Please fill this field', max_length=255, verbose_name='name')),
                ('tag_2', models.CharField(default='Please fill this field', max_length=255, verbose_name='lecturer')),
                ('type', models.CharField(choices=[('theoric', 'Theoric'), ('pratic', 'Pratic')], default='theoric', max_length=10)),
                ('picture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('lecturer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyprofile')),
                ('master', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qbank.coursemaster')),
            ],
        ),
    ]
