# Generated by Django 5.2.5 on 2025-08-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_phase_fk_committee_phase'),
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemaster',
            old_name='committe_pk',
            new_name='committe',
        ),
        migrations.RemoveField(
            model_name='coursemaster',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='coursemaster',
            name='lecturer_pk',
        ),
        migrations.AlterField(
            model_name='coursemaster',
            name='lecturer',
            field=models.ForeignKey(default=207, on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyprofile'),
        ),
    ]
