# Generated by Django 5.2.5 on 2025-08-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_phase_fk_committee_phase'),
        ('qbank', '0002_rename_committe_pk_coursemaster_committe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemaster',
            old_name='committe',
            new_name='committe_pk',
        ),
        migrations.AddField(
            model_name='coursemaster',
            name='committee',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coursemaster',
            name='lecturer_pk',
            field=models.ForeignKey(db_column='lecturer_pk_id', default=207, on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='coursemaster',
            name='lecturer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
