# Generated by Django 5.2.5 on 2025-08-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_rename_committe_coursemaster_committe_pk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemaster',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='coursemaster',
            name='lecturer',
        ),
    ]
