# Generated by Django 5.2.5 on 2025-08-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_phase_fk_committee_phase'),
        ('qbank', '0004_remove_coursemaster_committee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemaster',
            name='committe_pk',
        ),
        migrations.RemoveField(
            model_name='coursemaster',
            name='lecturer_pk',
        ),
        migrations.AddField(
            model_name='coursemaster',
            name='committe',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='cmt_courses', to='faculty.committee'),
        ),
        migrations.AddField(
            model_name='coursemaster',
            name='lecturer',
            field=models.ForeignKey(default=207, on_delete=django.db.models.deletion.CASCADE, related_name='fct_courses', to='faculty.facultyprofile'),
        ),
    ]
