# Generated by Django 5.2.5 on 2025-08-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0005_remove_coursemaster_committe_pk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemaster',
            old_name='committe',
            new_name='committee',
        ),
    ]
