# Generated by Django 5.2.5 on 2025-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0006_rename_committe_coursemaster_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaster',
            name='event_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
