# Generated by Django 5.2.5 on 2025-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0007_coursemaster_event_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequestiondepot',
            name='correct_feedback',
            field=models.TextField(blank=True, default='Doğru cevap.'),
        ),
        migrations.AlterField(
            model_name='coursequestiondepot',
            name='general_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coursequestiondepot',
            name='incorrect_feedback',
            field=models.TextField(blank=True, default='Yanlış cevap.'),
        ),
        migrations.AlterField(
            model_name='coursequestiondepot',
            name='partially_correct_feedback',
            field=models.TextField(blank=True, default='Kısmi olarak doğru.'),
        ),
    ]
