# Generated by Django 5.2.5 on 2025-09-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_alter_committee_chair'),
        ('qbank', '0008_alter_coursequestiondepot_correct_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('qtotal', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('theoric', 'Teorik'), ('pratic', 'Pratik'), ('final', 'Final'), ('final_pratic', 'Final Pratik')], default='theoric', max_length=12)),
                ('apply_penalty', models.BooleanField(default=True, help_text='If true, apply baraj/penalty scoring rule to all students')),
                ('locked', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.committee')),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.program')),
            ],
            options={
                'ordering': ['-date', 'start'],
            },
        ),
    ]
