# Generated by Django 5.2.5 on 2025-09-02 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0009_examsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestionSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qbank.examsetup')),
                ('master', models.ForeignKey(default=1200, on_delete=django.db.models.deletion.CASCADE, to='qbank.coursemaster')),
                ('question', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='qbank.coursequestiondepot')),
            ],
            options={
                'indexes': [models.Index(fields=['master'], name='qbank_cours_master__c21f85_idx'), models.Index(fields=['master', 'exam'], name='qbank_cours_master__7886f7_idx')],
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
