# Generated by Django 5.2.5 on 2025-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0010_coursequestionselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaster',
            name='final_question_set',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursemaster',
            name='question_set',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
