# Generated by Django 5.2.5 on 2025-08-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Temel Bilimler', 'Temel Bilimler'), ('Dahili Bilimler', 'Dahili Bilimler'), ('Cerrahi Bilimler', 'Cerrahi Bilimler')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dönem I', 'Dönem I'), ('Dönem II', 'Dönem II'), ('Dönem III', 'Dönem III'), ('Dönem IV', 'Dönem IV'), ('Dönem V', 'Dönem V'), ('Dönem VI', 'Dönem VI'), ('Dönem I_VI', 'Dönem I_VI')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('Dönem I', 'Dönem I'), ('Dönem II', 'Dönem II'), ('Dönem III', 'Dönem III'), ('Dönem IV', 'Dönem IV'), ('Dönem V', 'Dönem V'), ('Dönem VI', 'Dönem VI'), ('Dönem I_VI', 'Dönem I_VI')], max_length=11)),
                ('phase_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.program')),
            ],
        ),
    ]
