# Generated by Django 5.2.5 on 2025-08-24 17:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_department_program_committee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Teorik Yüzyüze', 'Teorik Yüzyüze'), ('Teorik Tersyüz Video', 'Teorik Tersyüz Video'), ('Teorik Tersyüz Tartışma', 'Teorik Tersyüz Tartışma'), ('Uygulama', 'Uygulama')], max_length=25)),
                ('acadyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.acadyear')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('period', models.BooleanField(default=True)),
                ('is_final', models.BooleanField(default=True)),
                ('edit_locked', models.BooleanField(default=False, help_text='Tüm düzenlemeler kilitli mi?')),
                ('acad_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acadyear_committeedepots', to='faculty.acadyear')),
                ('committee', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='cmt_committeedepots', to='faculty.committee')),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='pr_committeedepots', to='faculty.program')),
                ('chair', models.ForeignKey(default=207, on_delete=django.db.models.deletion.CASCADE, related_name='fct_committeedepots', to='faculty.facultyprofile')),
            ],
        ),
    ]
