# Generated by Django 5.2.5 on 2025-08-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_coursetype_facultyprofile_committeedepot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='phase',
        ),
    ]
