# Generated by Django 5.2.5 on 2025-08-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_committee_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='phase_fk',
            new_name='phase',
        ),
    ]
