# Generated by Django 5.2.5 on 2025-08-31 13:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_phase_fk_committee_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='chair',
            field=models.ForeignKey(default=207, on_delete=django.db.models.deletion.CASCADE, related_name='fct_committee', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='committee',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='committee',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
