# Generated by Django 5.2.5 on 2025-08-31 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_committee_chair_committee_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fct_committee', to='faculty.facultyprofile'),
        ),
    ]
