# Generated by Django 5.2.5 on 2025-09-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_alter_committee_chair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitteeDepot',
        ),
    ]
