# Generated by Django 5.2.5 on 2025-09-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_delete_committeedepot'),
        ('qbank', '0010_coursequestionselected'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenroll_courseevents', to='qbank.coursemaster', verbose_name='Course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fprofile_courseevents', to='faculty.facultyprofile', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Course Event',
                'verbose_name_plural': 'Course Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
